### ISSUE TITLE
Neovim: AttributeError("'LegacyVim' object has no attribute 'bindeval'",)

### ISSUE THREAD

**Issue by jakecraige** [mitsuse/neocomplete-kitten#1]
I'm trying to set this up using Neovim(0.1.4) and deocomplete and seeing this error when I trigger the omnifunc method with `<C-x><C-o>`

```
Error detected while processing function omni_swift#complete[6]..<SNR>177_complete[3]..autocomplete_swift#complete[9]..sourcekitten_daemon#complete[5]..<SNR>120_get[6]..<SNR>120_request[33]..13[94]..provider#python#Call:
line   18:
AttributeError("'LegacyVim' object has no attribute 'bindeval'",)
Traceback (most recent call last):
  File "/Users/jakecraige/Library/Python/2.7/lib/python/site-packages/neovim/msgpack_rpc/session.py", line 185, in handler
    rv = self._request_cb(name, args)
  File "/Users/jakecraige/Library/Python/2.7/lib/python/site-packages/neovim/api/nvim.py", line 151, in filter_request_cb
    result = request_cb(self._from_nvim(name), args)
  File "/Users/jakecraige/Library/Python/2.7/lib/python/site-packages/neovim/plugin/host.py", line 74, in _on_request
    rv = handler(*args)
  File "/Users/jakecraige/Library/Python/2.7/lib/python/site-packages/neovim/plugin/script_host.py", line 75, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 2, in <module>
AttributeError: 'LegacyVim' object has no attribute 'bindeval'
```

Any ideas on how to fix this?

**Comment by codelogicws** [comment]
Did you ever solve this because I have the same problem?

**Comment by jakecraige** [comment]
@codelogicws No I didn't. I haven't had time to look much more into it.

**Comment by mitsuse** [comment]
@jakecraige @codelogicws Sorry for late reply. I start investigating now, but I recommend to use with [deoplete](https://github.com/Shougo/deoplete.nvim) if you are not using it, which provides asynchronous autocompletion.

@codelogicws What the version of neovim are you using?

**Comment by mitsuse** [comment]
@jakecraige

> I'm trying to set this up using Neovim(0.1.4) and deocomplete

Sorry, I misunderstood. Omnifunc always uses the implementation in Vim script even if you use Neovim.

In addition, omnifunc avoids to send request to SourceKitten/SourceKittenDaemon when the regular expression doesn't match the current context (surrounding text). This regular expression is same as the one used for neocomplete/deoplete.

So, omnifunc is useless in the case that deoplete is installed.

**Comment by mitsuse** [comment]
@jakecraige @codelogicws 

This problem is reproduced with [`python-client`](https://github.com/neovim/python-client) for Python 2.x. The followings resolve this:
- Uninstall `python-client` for 2.x
- Use the 3.x version of `python-client`

I keep finding the fundamental resolution ... please wait for a while.

**Comment by mitsuse** [comment]
@jakecraige @codelogicws Is the problem solved? Please reopen this issue whenever the problem happens again.
