### ISSUE TITLE
How to install properly?

### ISSUE THREAD

**Issue by lyc2345** [mitsuse/neocomplete-kitten#10]
Hello, I see your repository that better than others swift vim plugin
I am a beginner to use vim like few months. Sorry for the easy questions.

I do install both dependencies
```
$ brew install sourcekitten
$ pip install pyyaml
```

And I install plugin use Vundle
```
Plugin 'Shougo/deoplete.nvim'
Plugin 'mitsuse/autocomplete-swift'
```
 and copy&paste below into my .vimrc
```
" Jump to the first placeholder by typing `<C-k>`.
autocmd FileType swift imap <buffer> <C-k> <Plug>(autocomplete_swift_jump_to_placeholder)
```
swift filetype
If your vim setup doesn't set *.swift file's filetype to swift you need to put this line in your config:
```
autocmd BufNewFile,BufRead *.swift set filetype=swift
```
But still not showing autocomplete for swift. So I think maybe I missing some steps from installing dependencies or setup my .vimrc

Could you please give me some hint or a simple tutorial for setting this up?

Thank you very much

**Comment by mitsuse** [comment]
@lyc2345 Thanks for reporting. Which are you using, Vim or NeoVIm? This plugin supports NeoVim only currently.

**Comment by mitsuse** [comment]
@lyc2345 I will close this issue, but please reopen this any time you like!
