### ISSUE TITLE
Include return type

### ISSUE THREAD

**Issue by drewdeponte** [mitsuse/neocomplete-kitten#11]
Is there any way to include the return type information in the autocompletion?

**Comment by drewdeponte** [comment]
I am guessing it is doable as the emacs sourcekitten based swift autocompletion plugin looks to do it

https://github.com/nathankot/company-sourcekit

**Comment by mitsuse** [comment]
@cyphactor Thank for your greate idea and suggestion! The return type informations are now presented on the completion window. Please try the new version of Autocomplete-swift!
<img width="1102" alt="screen shot 2018-06-13 at 0 21 44" src="https://user-images.githubusercontent.com/1525592/41300453-bf567864-6ea0-11e8-84e7-8e13607f9b32.png">
