### ISSUE TITLE
Vim Support

### ISSUE THREAD

**Issue by cansurmeli** [mitsuse/neocomplete-kitten#12]
Hello.

Is there any current work going on about having support for Vim? Or at least any plans for it in the near future?

**Comment by mitsuse** [comment]
@cansurmeli Sorry, there is no plan to support Vim currently.
However, Deoplete (Autocomplete-swift is a plugin for deoplete) supports Vim 8, you can add Vim 8 support to Autocomplete-swift and contributions are welcomed!
