### ISSUE TITLE
How to setup and use properly

### ISSUE THREAD

**Issue by ladislas** [mitsuse/neocomplete-kitten#13]
I'm having the exact same issue as #10.

I did all the install steps listed in the README and I'm using the latest version of Neovim with Python plugins installed.

The plugin doesn't seem to be 'running' as calling `echo g:autocomplete_swift#toolchain` or any other command results in an error message.

**Comment by ladislas** [comment]
Alright! So running `:UpdateRemotePlugins` seems to fix it! 

I now have completion. 

The only issue is that it's super slow and not showing everything as in your gif demo...

**Comment by ladislas** [comment]
Aaaaaand it's gone again...

:(

**Comment by krzysztof-magosa** [comment]
I use such config and it works for me.

```
Plugin 'apple/swift', {'rtp': 'utils/vim/'}
Plugin 'Shougo/deoplete.nvim'
Plugin 'mitsuse/autocomplete-swift'

let g:deoplete#sources#swift#daemon_autostart = 1
let g:deoplete#enable_at_startup = 1
```

**Comment by mitsuse** [comment]
@krzysztof-magosa Thanks for your comment!
