### ISSUE TITLE
Trouble setting this up

### ISSUE THREAD

**Issue by plm75** [mitsuse/neocomplete-kitten#3]
Hello, thanks for this plugin.

I'm having trouble setting it up however:

- neovim version 0.1.7
- source kitten installed v0.15.2
- source kitten deamon compiled from https://github.com/mitsuse/SourceKittenDaemon/tree/support-xcode8.0
- in init.vim:
'Shougo/deoplete.nvim'
'mitsuse/autocomplete-swift
let g:deoplete#enable_at_startup = 1

- I launch sourcekittendaemon as follows : SourceKittenDaemon start --port 44876 --project /path/to/myproject/myproject.xcodeproj

when I open a swift file, I get the basic deoplete completion (local file) but no project/framework completion.  In the sourcekittendaemon terminal, the server is working and listening but no calls are made.

Am I doing something wrong ?

**Comment by mitsuse** [comment]
@plm75 Hi, thanks for reporting.

Please execute`call sourcekitten_daemon#enable({port_number})` in Neovim after launching SourceKittenDaemon.

How many targets does your project include?
Unfortunately, SourceKittenDaemon cannot handle the project which contains multiple targets correctly according to my investigation...
