### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by KRUBERLICK** [mitsuse/neocomplete-kitten#8]
I have installed and configured everything as said in ReadMe.

What am I supposed to do after that? How to trigger completion list and do anything??

**Comment by mitsuse** [comment]
@KRUBERLICK Please confirm the configuration of deoplete.  If it is configured correctly, other completion features (for example, completion for file path) should be available. Candidates automatically shown in the popup menu.

**Comment by KRUBERLICK** [comment]
Here's my init.vim:
<img width="532" alt="screen shot 2017-01-24 at 15 31 34" src="https://cloud.githubusercontent.com/assets/16210297/22249086/379c2c7c-e24a-11e6-9544-61c52a97c6a9.png">
When I type something in this config file, for example Plug, autocompletion works and shows box with suggestions. 
<img width="535" alt="screen shot 2017-01-24 at 15 33 30" src="https://cloud.githubusercontent.com/assets/16210297/22249169/8484cdaa-e24a-11e6-977b-8dda59c98f6d.png">
However, I can't see anything when creating or opening .swift file.
Is there anything else I need to install or do?

**Comment by mitsuse** [comment]
@KRUBERLICK 

There seems to be no problem on the configuration of Neovim.

Can you show me the outputs of following shell/vim commands?

- In shell ...
  - `python --version`
  - `pip freeze`
  - `sourcekitten version`
  - `which sourcekitten`
- In Neovim
  - `:message`
  - `:call autocomplete_swift#use_toolchain('Swift_3_0')` and `:echo g:autocomplete_swift#toolchain`

**Comment by KRUBERLICK** [comment]
By default shell uses python 2.7, but in NeoVim I get 1 for :has("python3")
<img width="156" alt="screen shot 2017-01-24 at 16 32 44" src="https://cloud.githubusercontent.com/assets/16210297/22251300/ec8d0aa4-e252-11e6-9e84-b7dd20341840.png">
<img width="175" alt="screen shot 2017-01-24 at 16 34 52" src="https://cloud.githubusercontent.com/assets/16210297/22251340/15fb7a7e-e253-11e6-93da-a564b06920fa.png">
<img width="77" alt="screen shot 2017-01-24 at 16 34 59" src="https://cloud.githubusercontent.com/assets/16210297/22251343/18c235d6-e253-11e6-9fa0-a600cb737969.png">
```
$ pip freeze
alabaster==0.7.6
amqp==1.4.6
anyjson==0.3.3
Babel==2.0
backports-abc==0.4
backports.ssl-match-hostname==3.4.0.2
billiard==3.3.0.20
celery==3.1.18
certifi==2015.9.6.2
cycler==0.10.0
defusedxml==0.4.1
Django==1.9.7
django-braces==1.9.0
django-celery==3.1.16
django-cors-headers==1.1.0
django-crispy-forms==1.5.0
django-documentation==1.1
django-filter==0.14.0
django-oauth-toolkit==0.10.0
django-rest-framework-social-oauth2==1.0.4
djangorestframework==3.3.3
djangorestframework-jwt==1.8.0
docutils==0.12
greenlet==0.4.11
hiredis==0.2.0
httplib2==0.9.1
Jinja2==2.8
kombu==3.0.35
MarkupSafe==0.23
matplotlib==1.5.2
mock==2.0.0
msgpack-python==0.4.8
neovim==0.1.13
numpy==1.11.1
oauthlib==1.0.3
pbr==1.10.0
Pillow==2.9.0
Pygments==2.0.2
PyJWT==1.4.2
pyparsing==2.1.8
python-dateutil==2.5.3
python-openid==2.2.5
python-social-auth==0.2.19
python3-openid==3.0.10
pytz==2015.4
PyYAML==3.12
redis==2.10.5
requests==2.7.0
requests-oauthlib==0.6.2
singledispatch==3.4.0.3
six==1.9.0
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-rtd-theme==0.1.8
toredis==0.1.2
tornado==4.3
virtualenv==15.0.3
```
```
$ sourcekitten version
0.17.0
```
```
$ which sourcekitten
/usr/local/bin/sourcekitten
```
In NeoVim:
`:echo g:autocomplete_swift#toolchain`
<img width="278" alt="screen shot 2017-01-24 at 16 37 51" src="https://cloud.githubusercontent.com/assets/16210297/22251459/7f88159c-e253-11e6-9ad6-612365899c28.png">

**Comment by KRUBERLICK** [comment]
Okay, it seems working.
<img width="557" alt="screen shot 2017-01-24 at 16 41 56" src="https://cloud.githubusercontent.com/assets/16210297/22251617/1fdcb9b2-e254-11e6-8e0a-12df1afe0557.png">
So, this is a simple completion for swift syntax or it can look into other files with classes, when I open Xcode project or workspace?
Right now I'm able to get completions for data types as well as completion for class properties after typing dot(.).

**Comment by mitsuse** [comment]
Autocomplete-swift supports completion on a single file or a file contained in SPM project, not Xcode project.
[SourceKittenDaemon][github-sourcekittendaemon] may be available for the backend if you modify this plugin, but it has no support for workspace and multiple targets...

So, I'm working on the feature for better support for Xcode project.

[github-sourcekittendaemon]: https://github.com/terhechte/SourceKittenDaemon
